import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'te' | 'hi' | 'es' | 'fr' | 'ta' | 'mr' | 'de' | 'bn';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
];

export const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
  en: {
    appTitle: 'MediCare AI',
    navHome: 'Home / Dashboard',
    navProfile: 'My Profile',
    navSymptomSubmit: 'AI Diagnostics & Triage',
    navMedicalRecords: 'Medical Records History',
    navPrescriptionScanner: 'Prescription OCR Scanner',
    navPrescriptionTranslator: 'Medical AI Translator',
    navFraudDetection: 'Medicare Fraud AI',
    navDoctorCases: 'Patient Cases Review',
    navDoctorExport: 'Export Clinical Data',
    welcomeBack: 'Welcome to MediCare AI Portal',
    ocrScannerTitle: 'AI Medical Prescription OCR & Digitizer',
    ocrScannerSub: 'Upload or capture a prescription photo to extract drug names, dosages, frequencies, and instructions.',
    translatorTitle: 'Medical Prescription AI Translator & Shorthand Decoder',
    translatorSub: 'Translate prescriptions into regional & global languages while decoding prescription shorthand (b.i.d, p.o, q4h).',
    fraudTitle: 'CMS Medicare Fraud & Provider Anomaly Detection AI',
    fraudSub: 'Analyze provider NPI, Medicare Part D billing patterns, Schedule II/III opioid ratios, and LEIE exclusion compliance.',
    scanButton: 'Scan Prescription Image',
    translateButton: 'Translate Prescription',
    downloadPdf: 'Export PDF Card',
    confidenceScore: 'OCR Digitizer Confidence',
    extractedMedications: 'Extracted Medications',
    patientName: 'Patient Name',
    doctorName: 'Doctor Name',
    diagnosis: 'Diagnosis / Condition',
    medicationName: 'Medication Name',
    dosageInstructions: 'Dosage Instructions',
    frequency: 'Frequency',
    duration: 'Duration',
    shorthandExplanation: 'Decoded Medical Abbreviations',
    riskScore: 'Fraud Anomaly Risk Score',
    providerNpi: 'Provider NPI Number',
    startTriage: 'Start AI Diagnostics',
    viewRecords: 'View Records',
    editProfile: 'Edit Profile',
    checkFraud: 'Run Fraud Check',
    scanNotes: 'Scan Prescription',
    translateNotes: 'Translate Prescription Notes',
    recentCases: 'Recent Clinical Cases',
    selectLanguage: 'Select Language',
    hospitalAffiliation: 'Hospital / Clinic Affiliation',
    specialty: 'Medical Specialty',
    licenseNumber: 'License / NPI Number',
    patientPortalDesc: 'AI Symptom Triage, Prescription OCR Scan, & Multilingual Translator',
    doctorPortalDesc: 'Patient Case Management, Digital Prescription Suite, & Fraud Risk Indicators',
    adminPortalDesc: 'CMS Medicare Fraud Detection, LEIE Exclusion Checker, & System Audit',
  },
  te: {
    appTitle: 'మెడికేర్ AI',
    navHome: 'ముఖ్య పుట / డాష్‌బోర్డ్',
    navProfile: 'నా ప్రొఫైల్',
    navSymptomSubmit: 'AI రోగనిర్ధారణ & వర్గీకరణ',
    navMedicalRecords: 'వైద్య రికార్డుల చరిత్ర',
    navPrescriptionScanner: 'ప్రిస్క్రిప్షన్ OCR స్కానర్',
    navPrescriptionTranslator: 'వైద్య AI అనువాదకుడు',
    navFraudDetection: 'మెడికేర్ మోసాల AI నివేదిక',
    navDoctorCases: 'పేషెంట్ కేసుల సమీక్ష',
    navDoctorExport: 'వైద్య నివేదికల ఎగుమతి',
    welcomeBack: 'మెడికేర్ AI హెల్త్‌కేర్ పోర్టల్‌కు స్వాగతం',
    ocrScannerTitle: 'AI వైద్య ప్రిస్క్రిప్షన్ OCR & డిజిటైజర్',
    ocrScannerSub: 'ఔషధాల పేర్లు, మోతాదు మరియు సూచనలను సంగ్రహించడానికి ప్రిస్క్రిప్షన్ ఫోటోను అప్‌లోడ్ చేయండి.',
    translatorTitle: 'వైద్య ప్రిస్క్రిప్షన్ అనువాదకుడు & సంకేతాల వివరణ',
    translatorSub: 'ప్రిస్క్రిప్షన్లను తెలుగు మరియు ఇతర ప్రాంతీయ భాషలలోకి అనువదించండి (b.i.d, p.o, q4h సంకేతాల వివరణతో).',
    fraudTitle: 'CMS మెడికేర్ మోసాలు & ప్రొవైడర్ అసమానతల AI విశ్లేషణ',
    fraudSub: 'ప్రొవైడర్ NPI, బిల్లింగ్ విధానాలు మరియు ఒపియాయిడ్ నిష్పత్తులను విశ్లేషించండి.',
    scanButton: 'ప్రిస్క్రిప్షన్‌ను స్కాన్ చేయండి',
    translateButton: 'ప్రిస్క్రిప్షన్ అనువదించండి',
    downloadPdf: 'PDF కార్డ్ డౌన్‌లోడ్ చేయండి',
    confidenceScore: 'OCR డిజిటైజర్ కచ్చితత్వం స్కోరు',
    extractedMedications: 'సంగ్రహించిన ఔషధాల వివరాలు',
    patientName: 'పేషెంట్ పేరు',
    doctorName: 'డాక్టర్ పేరు',
    diagnosis: 'రోగ నిర్ధారణ / పరిస్థితి',
    medicationName: 'మందు పేరు',
    dosageInstructions: 'మోతాదు సూచనలు',
    frequency: 'ఫ్రీక్వెన్సీ (వాడే సమయం)',
    duration: 'కాలపరిమితి',
    shorthandExplanation: 'వైద్య సంకేతాల స్పష్టమైన వివరణ',
    riskScore: 'మోసం అసమానత రిస్క్ స్కోర్',
    providerNpi: 'ప్రొవైడర్ NPI సంఖ్య',
    startTriage: 'AI రోగనిర్ధారణ ప్రారంభించండి',
    viewRecords: 'రికార్డులు చూడండి',
    editProfile: 'ప్రొఫైల్ సవరించండి',
    checkFraud: 'మోసాల AI తనిఖీ చేయండి',
    scanNotes: 'ప్రిస్క్రిప్షన్ స్కాన్ చేయండి',
    translateNotes: 'సూచనలను అనువదించండి',
    recentCases: 'ఇటీవలి వైద్య కేసులు',
    selectLanguage: 'భాషను ఎంచుకోండి',
    hospitalAffiliation: 'ఆసుపత్రి / క్లినిక్ వివరాలు',
    specialty: 'వైద్య స్పెషాలిటీ',
    licenseNumber: 'లైసెన్స్ / NPI సంఖ్య',
    patientPortalDesc: 'AI లక్షణ విశ్లేషణ, ప్రిస్క్రిప్షన్ OCR స్కాన్ మరియు తెలుగు అనువాదకుడు',
    doctorPortalDesc: 'పేషెంట్ కేసుల నిర్వహణ, ప్రిస్క్రిప్షన్ స్కానర్ మరియు మోసాల తనిఖీ సూచికలు',
    adminPortalDesc: 'CMS మెడికేర్ మోసాల గుర్తింపు, LEIE బ్లాక్‌లిస్ట్ తనిఖీ మరియు సిస్టమ్ పర్యవేక్షణ',
  },
  hi: {
    appTitle: 'मेडीकेयर AI',
    navHome: 'मुख्य पृष्ठ / डैशबोर्ड',
    navProfile: 'मेरी प्रोफाइल',
    navSymptomSubmit: 'AI लक्षण निदान और वर्गीकरण',
    navMedicalRecords: 'चिकित्सा रिकॉर्ड इतिहास',
    navPrescriptionScanner: 'प्रिस्क्रिप्शन OCR स्कैनर',
    navPrescriptionTranslator: 'मेडिकल AI अनुवादक',
    navFraudDetection: 'मेडिकेयर फ्रॉड AI',
    navDoctorCases: 'रोगी मामलों की समीक्षा',
    navDoctorExport: 'मेडिकल डेटा निर्यात',
    welcomeBack: 'मेडीकेयर AI पोर्टल में आपका स्वागत है',
    ocrScannerTitle: 'AI मेडिकल प्रिस्क्रिप्शन OCR और डिजिटाइज़र',
    ocrScannerSub: 'दवा के नाम, खुराक और निर्देशों को निकालने के लिए प्रिस्क्रिप्शन फोटो अपलोड करें।',
    translatorTitle: 'मेडिकल प्रिस्क्रिप्शन AI अनुवादक और संक्षिप्त रूप व्याख्या',
    translatorSub: 'प्रिस्क्रिप्शन का हिंदी और अन्य भारतीय भाषाओं में अनुवाद करें (b.i.d, p.o, q4h जैसे संकेतों का अर्थ देखें)।',
    fraudTitle: 'CMS मेडिकेयर फ्रॉड और प्रदाता विसंगति जांच AI',
    fraudSub: 'प्रदाता NPI, बिलिंग पैटर्न और अफीम (Opioid) नुस्खे के अनुपात का विश्लेषण करें।',
    scanButton: 'प्रिस्क्रिप्शन स्कैन करें',
    translateButton: 'अनुवाद करें',
    downloadPdf: 'PDF कार्ड डाउनलोड करें',
    confidenceScore: 'OCR सटीकता स्कोर',
    extractedMedications: 'निकाली गई दवाएं',
    patientName: 'मरीज़ का नाम',
    doctorName: 'डॉक्टर का नाम',
    diagnosis: 'निदान / स्थिति',
    medicationName: 'दवा का नाम',
    dosageInstructions: 'खुराक निर्देश',
    frequency: 'आवृत्ति',
    duration: 'अवधि',
    shorthandExplanation: 'चिकित्सा संक्षिप्त रूपों की व्याख्या',
    riskScore: 'फ्रॉड जोखिम स्कोर',
    providerNpi: 'प्रदाता NPI संख्या',
    startTriage: 'AI निदान शुरू करें',
    viewRecords: 'रिकॉर्ड देखें',
    editProfile: 'प्रोफाइल संपादित करें',
    checkFraud: 'फ्रॉड AI जांचें',
    scanNotes: 'नुस्खा स्कैन करें',
    translateNotes: 'दवा निर्देश अनुवाद करें',
    recentCases: 'हाल के मेडिकल मामले',
    selectLanguage: 'भाषा चुनें',
    hospitalAffiliation: 'अस्पताल / क्लिनिक',
    specialty: 'चिकित्सा विशेषज्ञता',
    licenseNumber: 'लाइसेंस / NPI संख्या',
    patientPortalDesc: 'AI लक्षण निदान, प्रिस्क्रिप्शन OCR स्कैन और हिंदी अनुवादक',
    doctorPortalDesc: 'रोगी मामले प्रबंधन, डिजिटल प्रिस्क्रिप्शन और फ्रॉड रिस्क संकेतक',
    adminPortalDesc: 'CMS मेडिकेयर फ्रॉड जांच, LEIE ब्लैकलिस्ट चेकर और सिस्टम ऑडिट',
  },
  es: {
    appTitle: 'MediCare AI',
    navHome: 'Inicio / Panel',
    navProfile: 'Mi Perfil',
    navSymptomSubmit: 'Diagnóstico y Triaje por IA',
    navMedicalRecords: 'Historial de Registros Médicos',
    navPrescriptionScanner: 'Escáner OCR de Recetas',
    navPrescriptionTranslator: 'Traductor Médico por IA',
    navFraudDetection: 'Detección de Fraude Medicare',
    navDoctorCases: 'Revisión de Casos Clínicos',
    navDoctorExport: 'Exportación de Datos Clínicos',
    welcomeBack: 'Bienvenido al Portal MediCare AI',
    ocrScannerTitle: 'OCR y Digitalizador de Recetas Médicas por IA',
    ocrScannerSub: 'Cargue o tome una foto de la receta para extraer medicamentos, dosis y frecuencia.',
    translatorTitle: 'Traductor de Recetas Médicas y Decodificador de Abreviaturas',
    translatorSub: 'Traduzca recetas a múltiples idiomas y decodifique abreviaturas médicas (b.i.d, p.o, q4h).',
    fraudTitle: 'IA de Detección de Fraudes y Anomalías en Medicare (CMS)',
    fraudSub: 'Analice el NPI del proveedor, patrones de facturación y proporciones de opioides.',
    scanButton: 'Escanear Receta',
    translateButton: 'Traducir Receta',
    downloadPdf: 'Exportar Tarjeta PDF',
    confidenceScore: 'Precisión del Escáner OCR',
    extractedMedications: 'Medicamentos Extraídos',
    patientName: 'Nombre del Paciente',
    doctorName: 'Nombre del Médico',
    diagnosis: 'Diagnóstico / Condición',
    medicationName: 'Nombre del Medicamento',
    dosageInstructions: 'Instrucciones de Dosis',
    frequency: 'Frecuencia',
    duration: 'Duración',
    shorthandExplanation: 'Abreviaturas Médicas Decodificadas',
    riskScore: 'Puntuación de Riesgo de Fraude',
    providerNpi: 'Número NPI del Proveedor',
    startTriage: 'Iniciar Triaje con IA',
    viewRecords: 'Ver Registros',
    editProfile: 'Editar Perfil',
    checkFraud: 'Verificar Fraude',
    scanNotes: 'Escanear Receta',
    translateNotes: 'Traducir Receta',
    recentCases: 'Casos Clínicos Recientes',
    selectLanguage: 'Seleccionar Idioma',
    hospitalAffiliation: 'Hospital / Clínica',
    specialty: 'Especialidad Médica',
    licenseNumber: 'Número de Licencia / NPI',
    patientPortalDesc: 'Triaje de síntomas por IA, escáner OCR de recetas y traductor multilingüe',
    doctorPortalDesc: 'Gestión de casos de pacientes, suite de recetas digitales e indicadores de riesgo de fraude',
    adminPortalDesc: 'Detección de fraude Medicare CMS, verificador de listas de exclusión LEIE y auditoría',
  },
  fr: {
    appTitle: 'MediCare AI',
    navHome: 'Accueil / Tableau de bord',
    navProfile: 'Mon Profil',
    navSymptomSubmit: 'Diagnostic & Triage par IA',
    navMedicalRecords: 'Historique des Dossiers Médicaux',
    navPrescriptionScanner: 'Scanner OCR d Ordonnance',
    navPrescriptionTranslator: 'Traducteur Médical par IA',
    navFraudDetection: 'Détection Fraude Medicare',
    navDoctorCases: 'Examen des Dossiers Patients',
    navDoctorExport: 'Exportation de Données Cliniques',
    welcomeBack: 'Bienvenue sur le portail MediCare AI',
    ocrScannerTitle: 'OCR & Numériseur d Ordonnances Médicales par IA',
    ocrScannerSub: 'Téléchargez une photo d ordonnance pour extraire les médicaments, posologies et fréquences.',
    translatorTitle: 'Traducteur Médical & Décodeur d Abréviations',
    translatorSub: 'Traduisez vos ordonnances et décodez le jargon médical (b.i.d, p.o, q4h).',
    fraudTitle: 'IA de Détection des Fraudes & Anomalies Medicare CMS',
    fraudSub: 'Analysez les identifiants NPI des praticiens, la facturation et l usage des opioïdes.',
    scanButton: 'Scanner l Ordonnance',
    translateButton: 'Traduire l Ordonnance',
    downloadPdf: 'Exporter en PDF',
    confidenceScore: 'Indice de Confiance OCR',
    extractedMedications: 'Médicaments Extraits',
    patientName: 'Nom du Patient',
    doctorName: 'Nom du Médecin',
    diagnosis: 'Diagnostic / Pathologie',
    medicationName: 'Nom du Médicament',
    dosageInstructions: 'Instructions de Posologie',
    frequency: 'Fréquence',
    duration: 'Durée',
    shorthandExplanation: 'Abréviations Médicales Décodées',
    riskScore: 'Score de Risque de Fraude',
    providerNpi: 'Numéro NPI du Praticien',
    startTriage: 'Démarrer le Triage IA',
    viewRecords: 'Voir les Dossiers',
    editProfile: 'Modifier le Profil',
    checkFraud: 'Vérifier la Fraude',
    scanNotes: 'Scanner l Ordonnance',
    translateNotes: 'Traduire les Notes',
    recentCases: 'Dossiers Cliniques Récents',
    selectLanguage: 'Choisir la Langue',
    hospitalAffiliation: 'Hôpital / Clinique',
    specialty: 'Spécialité Médicale',
    licenseNumber: 'Numéro de Licence / NPI',
    patientPortalDesc: 'Triage des symptômes par IA, numérisation d ordonnances OCR et traducteur médical',
    doctorPortalDesc: 'Gestion des dossiers patients, ordonnances numérisées et indicateurs de fraude',
    adminPortalDesc: 'Détection des fraudes Medicare CMS, contrôle de la liste d exclusion LEIE et audit',
  },
  ta: {
    appTitle: 'மெடிகேர் AI',
    navHome: 'முகப்பு / கட்டுப்பாட்டுப் பலகம்',
    navProfile: 'எனது சுயவிவரம்',
    navSymptomSubmit: 'AI நோய் கண்டறிதல் & பகுப்பாய்வு',
    navMedicalRecords: 'மருத்துவப் பதிவுகளின் வரலாறு',
    navPrescriptionScanner: 'மருந்துச் சீட்டு OCR ஸ்கேனர்',
    navPrescriptionTranslator: 'மருத்துவ AI மொழிபெயர்ப்பாளர்',
    navFraudDetection: 'மெடிகேர் மோசடி தடுப்பு AI',
    navDoctorCases: 'நோயாளி வழக்குகள் ஆய்வு',
    navDoctorExport: 'மருத்துவ அறிக்கைகள் ஏற்றுமதி',
    welcomeBack: 'மெடிகேர் AI தளத்திற்கு வரவேற்கிறோம்',
    ocrScannerTitle: 'மருத்துவ சீட்டு AI OCR ஸ்கேனர்',
    ocrScannerSub: 'மருந்து பெயர்கள் மற்றும் அளவுகளை அறிய மருந்துச் சீட்டை பதிவேற்றவும்.',
    translatorTitle: 'மருத்துவச் சீட்டு AI மொழிபெயர்ப்பாளர் & சுருக்க விளக்க உரை',
    translatorSub: 'மருத்துவ சுருக்கங்களை (b.i.d, p.o, q4h) தமிழில் தெளிவாகப் புரிந்து கொள்ளுங்கள்.',
    fraudTitle: 'CMS மெடிகேர் மோசடி பகுப்பாய்வு AI',
    fraudSub: 'மருத்துவர் NPI மற்றும் பில்லிங் முறைகளை ஆராயுங்கள்.',
    scanButton: 'சீட்டை ஸ்கேன் செய்க',
    translateButton: 'சீட்டை மொழிபெயர்க்கவும்',
    downloadPdf: 'PDF பதிவிறக்கம்',
    confidenceScore: 'OCR துல்லிய அளவீடு',
    extractedMedications: 'பிரித்தெடுக்கப்பட்ட மருந்துகள்',
    patientName: 'நோயாளி பெயர்',
    doctorName: 'மருத்துவர் பெயர்',
    diagnosis: 'நோய் அறிதல் / நிலை',
    medicationName: 'மருந்து பெயர்',
    dosageInstructions: 'அளவு குறிப்புகள்',
    frequency: 'அதிர்வெண் (வாங்கும் நேரம்)',
    duration: 'கால அளவு',
    shorthandExplanation: 'மருத்துவ சுருக்கக் குறியீடுகளின் விளக்கம்',
    riskScore: 'மோசடி அபாயப் புள்ளி',
    providerNpi: 'வழங்குநர் NPI எண்',
    startTriage: 'AI சோதனையைத் தொடங்கவும்',
    viewRecords: 'பதிவுகளைப் பார்க்கவும்',
    editProfile: 'சுயவிவரத்தைத் திருத்தவும்',
    checkFraud: 'மோசடியைச் சோதிக்கவும்',
    scanNotes: 'சீட்டை ஸ்கேன் செய்யவும்',
    translateNotes: 'குறிப்புகளை மொழிபெயர்க்கவும்',
    recentCases: 'சமீபத்திய மருத்துவ வழக்குகள்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    hospitalAffiliation: 'மருத்துவமனை / கிளினிக்',
    specialty: 'மருத்துவத் துறை',
    licenseNumber: 'உரிமம் / NPI எண்',
    patientPortalDesc: 'AI அறிகுறி பகுப்பாய்வு, மருந்துச் சீட்டு OCR ஸ்கேன் மற்றும் தமிழ் மொழிபெயர்ப்பாளர்',
    doctorPortalDesc: 'நோயாளி வழக்குகள் நிர்வாகம், டிஜிட்டல் மருந்துச் சீட்டு மற்றும் மோசடி சோதனை',
    adminPortalDesc: 'CMS மெடிகேர் மோசடி பகுப்பாய்வு, LEIE கருப்புப்பட்டியல் சோதனை மற்றும் தணிக்கை',
  },
  mr: {
    appTitle: 'मेडिकेअर AI',
    navHome: 'मुख्य पृष्ठ / डॅशबोर्ड',
    navProfile: 'माझी प्रोफाइल',
    navSymptomSubmit: 'AI लक्षण निदान आणि वर्गीकरण',
    navMedicalRecords: 'वैद्यकीय रेकॉर्ड इतिहास',
    navPrescriptionScanner: 'प्रिस्क्रिप्शन OCR स्कॅनर',
    navPrescriptionTranslator: 'मेडिकल AI अनुवादक',
    navFraudDetection: 'मेडिकेअर फ्रॉड AI',
    navDoctorCases: 'रुग्ण प्रकरणांचे पुनरावलोकन',
    navDoctorExport: 'वैद्यकीय डेटा निर्यात',
    welcomeBack: 'मेडिकेअर AI पोर्टलवर आपले स्वागत आहे',
    ocrScannerTitle: 'AI वैद्यकीय प्रिस्क्रिप्शन OCR आणि डिजिटायझर',
    ocrScannerSub: 'औषधांची नावे, डोस आणि सूचना काढण्यासाठी प्रिस्क्रिप्शन फोटो अपलोड करा.',
    translatorTitle: 'वैद्यकीय प्रिस्क्रिप्शन AI अनुवादक आणि संक्षिप्त रूप स्पष्टीकरण',
    translatorSub: 'प्रिस्क्रिप्शनचा मराठी आणि इतर भाषांमध्ये अनुवाद करा (b.i.d, p.o, q4h स्पष्टीकरणासह).',
    fraudTitle: 'CMS मेडिकेअर फ्रॉड आणि प्रदाता विसंगती तपासणी AI',
    fraudSub: 'प्रदाता NPI, बिलिंग पॅटर्न आणि ओपिऑइड औषध प्रमाणाचे विश्लेषण करा.',
    scanButton: 'प्रिस्क्रिप्शन स्कॅन करा',
    translateButton: 'अनुवाद करा',
    downloadPdf: 'PDF कार्ड डाउनलोड करा',
    confidenceScore: 'OCR अचूकता गुण',
    extractedMedications: 'काढलेली औषधे',
    patientName: 'रुग्णाचे नाव',
    doctorName: 'डॉक्टरांचे नाव',
    diagnosis: 'निदान / स्थिती',
    medicationName: 'औषधाचे नाव',
    dosageInstructions: 'डोस सूचना',
    frequency: 'वारंवारता',
    duration: 'कालावधी',
    shorthandExplanation: 'वैद्यकीय संक्षिप्त रूपांचे स्पष्टीकरण',
    riskScore: 'फ्रॉड जोखीम गुण',
    providerNpi: 'प्रदाता NPI क्रमांक',
    startTriage: 'AI निदान सुरू करा',
    viewRecords: 'रेकॉर्ड पहा',
    editProfile: 'प्रोफाइल संपादित करा',
    checkFraud: 'फ्रॉड AI तपासा',
    scanNotes: 'प्रिस्क्रिप्शन स्कॅन करा',
    translateNotes: 'सूचनांचा अनुवाद करा',
    recentCases: 'अलीकडील वैद्यकीय प्रकरणे',
    selectLanguage: 'भाषा निवडा',
    hospitalAffiliation: 'रुग्णालय / क्लिनिक',
    specialty: 'वैद्यकीय तज्ज्ञता',
    licenseNumber: 'परवाना / NPI क्रमांक',
    patientPortalDesc: 'AI लक्षण निदान, प्रिस्क्रिप्शन OCR स्कॅन आणि मराठी अनुवादक',
    doctorPortalDesc: 'रुग्ण प्रकरण व्यवस्थापन, डिजिटल प्रिस्क्रिप्शन आणि फ्रॉड रिस्क निर्देशक',
    adminPortalDesc: 'CMS मेडिकेअर फ्रॉड तपासणी, LEIE ब्लॉकलिस्ट चेकर आणि सिस्टम ऑडिट',
  },
  de: {
    appTitle: 'MediCare AI',
    navHome: 'Startseite / Dashboard',
    navProfile: 'Mein Profil',
    navSymptomSubmit: 'KI-Symptomdiagnose & Triage',
    navMedicalRecords: 'Krankenakte Historie',
    navPrescriptionScanner: 'Rezept OCR Scanner',
    navPrescriptionTranslator: 'Medizinischer KI-Übersetzer',
    navFraudDetection: 'Medicare Betrugs-KI',
    navDoctorCases: 'Patientenfälle Prüfen',
    navDoctorExport: 'Klinische Daten Exportieren',
    welcomeBack: 'Willkommen beim MediCare AI Portal',
    ocrScannerTitle: 'KI-Rezept OCR & Digitalisierer',
    ocrScannerSub: 'Laden Sie ein Rezeptfoto hoch, um Medikamente, Dosierungen und Anweisungen zu extrahieren.',
    translatorTitle: 'Medizinischer KI-Rezeptübersetzer & Kürzel-Decoder',
    translatorSub: 'Übersetzen Sie Rezepte in verschiedene Sprachen und dekodieren Sie medizinische Kürzel (b.i.d, p.o, q4h).',
    fraudTitle: 'CMS Medicare Betrugs- & Anomalie-Erkennungs-KI',
    fraudSub: 'Analysieren Sie NPI-Nummern, Abrechnungsmuster und Opioid-Verschreibungsquoten.',
    scanButton: 'Rezept Scannen',
    translateButton: 'Rezept Übersetzen',
    downloadPdf: 'PDF-Karte Exportieren',
    confidenceScore: 'OCR-Genauigkeitsscore',
    extractedMedications: 'Extrahierte Medikamente',
    patientName: 'Patientenname',
    doctorName: 'Arztname',
    diagnosis: 'Diagnose / Befund',
    medicationName: 'Medikamentenname',
    dosageInstructions: 'Dosierungsanweisungen',
    frequency: 'Häufigkeit',
    duration: 'Dauer',
    shorthandExplanation: 'Dekodierte Medizinische Abkürzungen',
    riskScore: 'Betrugs-Risikoscore',
    providerNpi: 'Anbieter NPI-Nummer',
    startTriage: 'KI-Diagnose Starten',
    viewRecords: 'Akten Anzeigen',
    editProfile: 'Profil Bearbeiten',
    checkFraud: 'Betrugs-KI Prüfen',
    scanNotes: 'Rezept Scannen',
    translateNotes: 'Anweisungen Übersetzen',
    recentCases: 'Aktuelle Klinische Fälle',
    selectLanguage: 'Sprache Auswählen',
    hospitalAffiliation: 'Krankenhaus / Klinik',
    specialty: 'Fachgebiet',
    licenseNumber: 'Lizenz / NPI-Nummer',
    patientPortalDesc: 'KI-Symptom-Triage, Rezept-OCR-Scan und mehrsprachiger Übersetzer',
    doctorPortalDesc: 'Patientenfall-Management, digitale Rezepte und Betrugsrisiko-Indikatoren',
    adminPortalDesc: 'CMS Betrugserkennung, LEIE-Ausschlussprüfung und System-Audit',
  },
  bn: {
    appTitle: 'মেডিকেয়ার AI',
    navHome: 'হোম পেজ / ড্যাশবোর্ড',
    navProfile: 'আমার প্রোফাইল',
    navSymptomSubmit: 'AI লক্ষণ নির্ণয় ও শ্রেণীবদ্ধকরণ',
    navMedicalRecords: 'মেডিকেল রেকর্ডের ইতিহাস',
    navPrescriptionScanner: 'প্রেসক্রিপশন OCR স্ক্যানার',
    navPrescriptionTranslator: 'মেডিকেল AI অনুবাদক',
    navFraudDetection: 'মেডিকেয়ার ফ্রড AI',
    navDoctorCases: 'রোগীর কেস পর্যালোচনা',
    navDoctorExport: 'মেডিকেল ডেটা রপ্তানি',
    welcomeBack: 'মেডিকেয়ার AI পোর্টালে আপনাকে স্বাগতম',
    ocrScannerTitle: 'AI মেডিকেল প্রেসক্রিপশন OCR এবং ডিজিটাইজার',
    ocrScannerSub: 'ঔষধের নাম, মাত্রা এবং নির্দেশনা বের করতে প্রেসক্রিপশনের ছবি আপলোড করুন।',
    translatorTitle: 'মেডিকেল প্রেসক্রিপশন AI অনুবাদক ও সংক্ষেপ ব্যাখ্যা',
    translatorSub: 'প্রেসক্রিপশন বাংলায় অনুবাদ করুন এবং সংকটাপন্ন কোডগুলোর (b.i.d, p.o, q4h) অর্থ বুঝুন।',
    fraudTitle: 'CMS মেডিকেয়ার ফ্রড ও অসঙ্গতি বিশ্লেষণ AI',
    fraudSub: 'প্রোভাইডার NPI, বিলিং প্যাটার্ন এবং ওপিওয়েড প্রেসক্রিপশন অনুপাত বিশ্লেষণ করুন।',
    scanButton: 'প্রেসক্রিপশন স্ক্যান করুন',
    translateButton: 'অনুবাদ করুন',
    downloadPdf: 'PDF কার্ড ডাউনলোড করুন',
    confidenceScore: 'OCR নির্ভুলতা স্কোর',
    extractedMedications: 'সংগৃহীত ঔষধের তালিকা',
    patientName: 'রোগীর নাম',
    doctorName: 'ডাক্তারের নাম',
    diagnosis: 'রোগ নির্ণয় / অবস্থা',
    medicationName: 'ঔষধের নাম',
    dosageInstructions: 'মাত্রার নির্দেশাবলী',
    frequency: 'ঘনত্ব (খাওয়ার সময়)',
    duration: 'সময়কাল',
    shorthandExplanation: 'মেডিকেল সংক্ষিপ্ত রূপের অর্থ',
    riskScore: 'ফ্রড ঝুঁকির স্কোর',
    providerNpi: 'প্রোভাইডার NPI নম্বর',
    startTriage: 'AI রোগ নির্ণয় শুরু করুন',
    viewRecords: 'রেকর্ড দেখুন',
    editProfile: 'প্রোফাইল সম্পাদনা করুন',
    checkFraud: 'ফ্রড AI পরীক্ষা করুন',
    scanNotes: 'প্রেসক্রিপশন স্ক্যান করুন',
    translateNotes: 'নির্দেশাবলী অনুবাদ করুন',
    recentCases: 'সাম্প্রতিক মেডিকেল কেস',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    hospitalAffiliation: 'হাসপাতাল / ক্লিনিক',
    specialty: 'মেডিকেল বিশেষজ্ঞতা',
    licenseNumber: 'লাইসেন্স / NPI নম্বর',
    patientPortalDesc: 'AI লক্ষণ বিশ্লেষণ, প্রেসক্রিপশন OCR স্ক্যান এবং বাংলা অনুবাদক',
    doctorPortalDesc: 'রোগীর কেস ব্যবস্থাপনা, ডিজিটাল প্রেসক্রিপশন এবং ফ্রড ঝুঁকি সূচক',
    adminPortalDesc: 'CMS মেডিকেয়ার ফ্রড বিশ্লেষণ, LEIE ব্লকলিস্ট চেক এবং সিস্টেম অডিট',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    const saved = localStorage.getItem('medicare_language') as LanguageCode;
    if (saved && SUPPORTED_LANGUAGES.some((l) => l.code === saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('medicare_language', lang);
  };

  const t = (key: string): string => {
    return DICTIONARY[language]?.[key] || DICTIONARY['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
